name: Publish to WinGet

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-slim
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Qubernetic.copia-cli
          installers-regex: '\.zip$'
          max-versions-to-keep: 5
          token: ${{ secrets.WINGET_TOKEN }}
